name: Hello world
run-name: Hello world ${{ inputs.name }} execution

on:
  workflow_dispatch:
    inputs:
      name:
        description: "provide your first name"
        required: true
        type: "string"
      last_name:
        description: "provide your last name"
        required: true
        type: "string"

jobs:
  print_name:
    runs-on: ubuntu-latest
    steps: 
      - name: Echo name to console 
        run: echo "Hello ${{ inputs.name }}! Wlcome to the first step"

  print_last_name:
    outputs: 
      last_name_length: ${{ steps.count_characters.outputs.length }}
    runs-on: ubuntu-latest
    steps: 
      - name: Echo name to console 
        run: |
          echo "Hello ${{ inputs.last_name }}! Wlcome to the first step"

      - name: Count characters in last name
        id: count_characters
        run: |
          last_name=${{ inputs.last_name }}
          length=${#last_name}

          # Export output within the step
          echo "length=$length" >> $GITHUB_OUTPUT

    
